services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: poetry run uvicorn src.app:app --host 0.0.0.0 --port 8000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    networks:
      - app-network
    depends_on:
      - postgres
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: